### ISSUE TITLE
refactor(models): abstractions of each image file

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/6ow3idGirl#21]
## AsIs
Currently the images of each releases and thumbnails are implemented as static contents, but for allowing the site more dynamically, need to use express models to retrieve image path, or itselves.

## ToDo
- [x] fix ORM solutions with TypeScript for Nest(Express)
- [x] add code bases of models, where we would define database schemas to use

## (Optional) Acceptances
- [x] confirm we can use migration features provided by ORMs without any error
- [x] confirm database schemas will be applied to MySQL server on GCE instance

## (Optional) Additional contexts
- The MySQL database to apply Nest(Express) models have been already provisioned as GCE instance in #68.
- **The database on GCE instance is used and shared between several projects**, which are also hosted on same GKE cluster as this application.

**Comment by hwakabh** [comment]
https://docs.nestjs.com/techniques/database

**Comment by hwakabh** [comment]
> confirm database schemas will be applied to MySQL server on GCE instance

We confirmed this with local MySQL container instead of GCE instances, since the production GKE cluster is making error on cluster-side, so will mark as completed so far.
