### ISSUE TITLE
ci: setup default labels and labeler

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/6ow3idGirl#43]
## AsIs
Currently we use default lables, and almost all of them are not used.

## ToDo
- [x] initialize default labels for development with using `@azu/github-label-setup`
- [x] add `github/issue-labeler` for issue
- [x] add `actions/labeler` for PR
