### ISSUE TITLE
build: deployment on GKE with custom domain and TLS

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/6ow3idGirl#51]
# AsIs
Although we have successfully deployed Express app on GKE, still its serviceType is `ClusterIP` and application has not been published towards internet.
To resolve this, we have to implement Kubernetes ingress resource, and configure it with TLS considering production access via custom domains.

# ToDo
- [x] install cert-manager on GKE cluster
- [x] add issuer resource with Let's Encrypt
- [x] generate TLS certifications for custom domain

# (Optional) Acceptance criteria
- confirm all the resource related are running without any error
- confirm we can access applications to custom domain with TLS (https://6ow3idgirl.com)

# (Optional) Additional contexts
Issue(s): #41 
Since we have already installed ingress-nginx controller on GKE cluster [with another project](https://github.com/hwakabh/bennu-official/issues/164), there is no task needed to install ingress-nginx here.

**Comment by hwakabh** [comment]
Note for GKE deployment:

```shell
24-03-01 23:32:20 git/6ow3idGirl [main] % gcloud compute addresses create ext-nginx-ingress --region us-central1
Created [https://www.googleapis.com/compute/v1/projects/hwakabh-dev/regions/us-central1/addresses/ext-nginx-ingress].

24-03-01 23:32:54 git/6ow3idGirl [main] % gcloud compute addresses list                                         
NAME               ADDRESS/RANGE   TYPE      PURPOSE  NETWORK  REGION       SUBNET  STATUS
ext-nginx-ingress  35.232.222.128  EXTERNAL                    us-central1          RESERVED

24-03-02 0:12:24 git/6ow3idGirl [main] % kubectl -n ingress-nginx get services   
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.100.9.84     35.232.222.128   80:30571/TCP,443:32591/TCP   30d
ingress-nginx-controller-admission   ClusterIP      10.100.10.230   <none>           443/TCP                      30d
```

**Comment by hwakabh** [comment]
Confirmed that all resources are deployed without any error after applying manifests in PR.

```shell
24-03-02 0:13:57 git/6ow3idGirl [main] % kubectl -n 6ow3idgirl get issuers,challenges,orders,crs,certs,clusterissuers,secrets
NAME                                 READY   AGE
issuer.cert-manager.io/letsencrypt   True    85m

NAME                                               STATE   AGE
order.acme.cert-manager.io/tls-cert-1-2479354409   valid   7m27s

NAME                                            APPROVED   DENIED   READY   ISSUER        REQUESTOR                                         AGE
certificaterequest.cert-manager.io/tls-cert-1   True                True    letsencrypt   system:serviceaccount:cert-manager:cert-manager   7m27s

NAME                                   READY   SECRET     AGE
certificate.cert-manager.io/tls-cert   True    tls-cert   7m28s

NAME                    TYPE                DATA   AGE
secret/ca-letsencrypt   Opaque              1      85m
secret/tls-cert         kubernetes.io/tls   2      7m27s

24-03-02 0:14:12 git/6ow3idGirl [main] % kubectl -n 6ow3idgirl get ingress                                                   
NAME   CLASS   HOSTS            ADDRESS          PORTS     AGE
app    nginx   6ow3idgirl.com   35.232.222.128   80, 443   14m

# application access with TLS
24-03-02 3:30:36 git/6ow3idGirl [build/51/deployment] % curl -D - -o /dev/null -s -X GET https://6ow3idgirl.com
HTTP/2 200 
date: Fri, 01 Mar 2024 18:30:46 GMT
content-type: text/html; charset=utf-8
content-length: 17396
x-powered-by: Express
etag: W/"43f4-rnvat1TLASIZ3pj7i3KfZCFOXcA"
strict-transport-security: max-age=31536000; includeSubDomains
```
