### ISSUE TITLE
migrations to Nest from Express

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/6ow3idGirl#57]
# AsIs
Since we have already had several Express projects in other repository, for dog foodings, we have decided to adopt [Nest](https://nestjs.com) in this project.

Referenced its [official documentations](https://docs.nestjs.com), Nest is compatible with Express, where Nest will use Express internally by default with its modular system, and it seems that we can reuse current code bases generated by `express-generator` with adding Nest on top of them.
> Nest provides a level of abstraction above these common Node.js frameworks (Express/Fastify), but also exposes their APIs directly to the developer. 

As we have options to use either JavaScript or TypeScript with Nest, we should use TypeScript for developing type-safed application, for reducing errors in coding, and so forth.
(We can see both starter project [for TypeScript](https://github.com/nestjs/typescript-starter) and [for JavaScript](https://github.com/nestjs/javascript-starter) in [Nest GitHub organization](https://github.com/nestjs).
> It uses progressive JavaScript, is built with and fully supports TypeScript (yet still enables developers to code in pure JavaScript) 

So this means that we have to refactor current code base from `.js` to `.ts`, and there are several points as efficient frameworb migration.

# ToDo
- [x] add Nest minimal code base on top of Express
- [x] migrate Express features to Nest
- [x] implement TypeScript in application

# (Optional) Acceptance criteria
We can start up Nest project with integrating current codes

# (Optional) Additional contexts
N/A

**Comment by hwakabh** [comment]
Still we need to add ORMs of Nest, TypeScript, but we could successfully migrate Express.js application to Nest with running Express with TypeScript as its backend, we can close this issue for now.

As [commented](https://github.com/hwakabh/6ow3idGirl/issues/21#issuecomment-1986743924) in another issue, regarding implementations of ORM for Nest, we will manage this issue separately.
