### ISSUE TITLE
refactor(views): loops of model instances

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/6ow3idGirl#80]
# AsIs
Currently the release entities (Music and Movie) are hard coded in Nest views, `src/views/home.pug`.
Since we had already implemented Nest models, which interact with MySQL database via TypeORM, need to refactor them to fetch data via Nest controllers/services and render with loops in Pug templates.

# ToDo
- [x] remove hard coded music/movies from current views
- [x] enable to fetch data from MySQL via controller/services
- [x] render with loop in views

# (Optional) Acceptance criteria
UI would not be changed after running `npm run start`

# (Optional) Additional contexts
Issue(s): #21, #101
